### ISSUE TITLE
500 Internal Server Errorが発生している

### ISSUE THREAD

**Issue by hato810424** [sya-ri/spigot-event-list#1252]
https://spigot-event-list.s7a.dev/ のレスポンスが`500 Internal Server Error`になっていて見ることができなくなっています

**Comment by sya-ri** [comment]
500 Internal Server Error は一時的なものだったかもしれません。エラーが起きた場合はスクリーンショットやログを添付していただけると助かります。検索に関してバグがあったのでそれについては修正しました

**Comment by hato810424** [comment]
失礼しました、添付しますね
アドレスは両方とも spigot-event-list.s7a.dev にアクセスした際のログで、拡張機能は切ってあります

---

Chromium
![image](https://github.com/sya-ri/spigot-event-list/assets/74600008/21fe068a-2a96-46bb-b7fa-f384e6eb7443)

Firefox
![image](https://github.com/sya-ri/spigot-event-list/assets/74600008/f96a1c7c-88f1-44cd-b0b2-1c2b858bad17)

**Comment by sya-ri** [comment]
おそらく locale が default の状態でアクセスすると、上手く言語取得ができずにエラーになるのかな～と言ったところです。修正してみました。

**Comment by hato810424** [comment]
無事 表示できました、助かります～！
![image](https://github.com/sya-ri/spigot-event-list/assets/74600008/f6763b2c-3a47-40ce-a5ac-48d03b46afaa)
