### ISSUE TITLE
Velocityの追加

### ISSUE THREAD

**Issue by rona-tombo** [sya-ri/spigot-event-list#133]
**Download**: https://velocitypowered.com/downloads
PaperMC傘下に入ったのでダウンロード元が近いうちに変わるかもしれません

**JavaDoc Overview**: https://jd.velocitypowered.com/3.0.0/index.html

**JavaDoc AllClasses**: https://jd.velocitypowered.com/3.0.0/allclasses.html

**JavaDoc Deprecated List**: https://jd.velocitypowered.com/3.0.0/deprecated-list.html

**Comment by sya-ri** [comment]
ありがとうございます！対応させていただきます！！

ウェブページの改善を合わせてするかもしれないので、遅れてしまうかもしれませんがご理解いただけると幸いです。
