### ISSUE TITLE
ConversationAbandonedEvent の説明が分からない

### ISSUE THREAD

**Issue by sya-ri** [sya-ri/spigot-event-list#3]
**Event**: ConversationAbandonedEvent

ConversationAbandonedEvent というイベントがどう言う状況で発生するのかを知らないので「不明。」という説明になっている。

**Comment by mirror-kt** [comment]
![スクリーンショット 2021-02-08 20 38 57](https://user-images.githubusercontent.com/43880251/107214769-bd8b9680-6a4d-11eb-8bcf-c4117a27c33d.png)
decompileして内部実装を読んでみたりもしましたが、`org.bukkit.event.Event` との継承関係がないのでおそらく内部処理用のクラスだと思います。

**Comment by sya-ri** [comment]
おっしゃる通り、 `org.bukkit.event.Event` を継承していないクラスですね。あくまで `Event` で終わるクラスのみを抽出しているのでこのようなことになっていまったようです。指定したイベントは例外として追加しないようにしておきます。ありがとうございます。
